Traceback (most recent call last):
  File "d:\github projects\reflectorch\reflectorch\.venv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "d:\github projects\reflectorch\reflectorch\.venv\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "d:\github projects\reflectorch\reflectorch\.venv\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\valen\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "d:\github projects\reflectorch\reflectorch\.venv\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "d:\github projects\reflectorch\reflectorch\.venv\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "d:\github projects\reflectorch\reflectorch\.venv\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
torch.load(save_path).keys()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [1;32mIn[8], line 1[0m
[1;32m----> 1[0m [43mtorch[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[43msave_path[49m[43m)[49m[38;5;241m.[39mkeys()

File [1;32md:\github projects\reflectorch\reflectorch\.venv\lib\site-packages\torch\serialization.py:998[0m, in [0;36mload[1;34m(f, map_location, pickle_module, weights_only, mmap, **pickle_load_args)[0m
[0;32m    995[0m [38;5;28;01mif[39;00m [38;5;124m'[39m[38;5;124mencoding[39m[38;5;124m'[39m [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m pickle_load_args[38;5;241m.[39mkeys():
[0;32m    996[0m     pickle_load_args[[38;5;124m'[39m[38;5;124mencoding[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;124m'[39m[38;5;124mutf-8[39m[38;5;124m'[39m
[1;32m--> 998[0m [38;5;28;01mwith[39;00m [43m_open_file_like[49m[43m([49m[43mf[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m opened_file:
[0;32m    999[0m     [38;5;28;01mif[39;00m _is_zipfile(opened_file):
[0;32m   1000[0m         [38;5;66;03m# The zipfile reader is going to advance the current file position.[39;00m
[0;32m   1001[0m         [38;5;66;03m# If we want to actually tail call to torch.jit.load, we need to[39;00m
[0;32m   1002[0m         [38;5;66;03m# reset back to the original position.[39;00m
[0;32m   1003[0m         orig_position [38;5;241m=[39m opened_file[38;5;241m.[39mtell()

File [1;32md:\github projects\reflectorch\reflectorch\.venv\lib\site-packages\torch\serialization.py:445[0m, in [0;36m_open_file_like[1;34m(name_or_buffer, mode)[0m
[0;32m    443[0m [38;5;28;01mdef[39;00m [38;5;21m_open_file_like[39m(name_or_buffer, mode):
[0;32m    444[0m     [38;5;28;01mif[39;00m _is_path(name_or_buffer):
[1;32m--> 445[0m         [38;5;28;01mreturn[39;00m [43m_open_file[49m[43m([49m[43mname_or_buffer[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m
[0;32m    446[0m     [38;5;28;01melse[39;00m:
[0;32m    447[0m         [38;5;28;01mif[39;00m [38;5;124m'[39m[38;5;124mw[39m[38;5;124m'[39m [38;5;129;01min[39;00m mode:

File [1;32md:\github projects\reflectorch\reflectorch\.venv\lib\site-packages\torch\serialization.py:426[0m, in [0;36m_open_file.__init__[1;34m(self, name, mode)[0m
[0;32m    425[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, name, mode):
[1;32m--> 426[0m     [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m([38;5;28;43mopen[39;49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m)

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'D:\\Github Projects\\reflectorch\\reflectorch\\saved_models\\model_c1.pt'

